### PR TITLE
Add support for injecting Bundle when creating RiveFile

### PR DESCRIPTION
**Pull request by RobertDresler**

### CODE REVIEW

**Comment by davidscheutz** [comment]
Let's get this reviewed and merged please 🙌

**Comment by ilyakuteev** [comment]
Hey @RobertDresler, I've created an issue https://github.com/rive-app/rive-ios/issues/259 showing the problem with unconditional main bundle usage.

Seems like your PR fixes this issue.

**Comment by ilyakuteev** [comment]
Maybe we should also use this method here: https://github.com/rive-app/rive-ios/blob/4.0.2/Tests/RiveDelegatesTest.swift#L19?
This would make tests more clear and also will make sure that bundle parameter is working correctly.

**Comment by JustJakeRyan** [comment]
Let's get this PR merged asap. Unfortunately, this issue blocks our entire team.

**Comment by zplata** [comment]
Hi! Sorry for the silence here - we'll get this change merged in shortly

**Comment by zplata** [comment]
Hey all - [this change](https://github.com/rive-app/rive-ios/commit/1b78705768a1cd84bc2f5bb76551932bffce0585) was merged from our upstream repo and released in `v4.0.3`. Thanks for your contribution @RobertDresler!

**Pull request closed without merging**
